# src/configs/tool_call_patterns.yaml

patterns:
  # JSON Array Format with Double Quotes
  JsonArrayPattern0: '[{"name'
  JsonArrayPattern1: '[{\"name'
  JsonArrayPattern2: '[{\\"name'

  # JSON Array Format with Single Quotes
  JsonArrayPattern3: "[{'name"
  JsonArrayPattern4: "[{'name"
  JsonArrayPattern5: "[{\\'name"

  # Function Call Formats with Double Quotes
  FunctionCallPattern0: '<function='
  FunctionCallPattern1: '{"name'

  # Function Call Formats with Single Quotes
  FunctionCallPattern2: "{'name"

  # Tool Call Tag Formats
  ToolCallTagPattern0: '<|tool_call|>'
  ToolCallTagPattern1: '<tool_call>'
  ToolCallTagPattern2: '[TOOL_CALL]'
  ToolCallTagPattern3: '[tool_call]'

  # Tool Calls Tag Formats
  ToolCallsTagPattern0: '<|tool_calls|>'
  ToolCallsTagPattern1: '<tool_calls>'
  ToolCallsTagPattern2: '[TOOL_CALLS]'

  # Code Block Formats with Double Quotes
  CodeBlockPattern0: '```[{"name'
  CodeBlockPattern1: '```json[{"name'
  CodeBlockPattern2: '```{"name'
  CodeBlockPattern3: '```json{"name'

  # Code Block Formats with Single Quotes
  CodeBlockPattern4: "```[{'name"
  CodeBlockPattern5: "```json[{'name"
  CodeBlockPattern6: "```{'name"
  CodeBlockPattern7: "```json{'name"

  # Programming Language Tags
  LanguageTagPattern0: '<|python_tag|>'
